name: Ubuntu unit tests
on:
  push:
    branches:
      - main

jobs:

  build-and-test:
    name: unit-ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Configure Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64

      - name: Install
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .[dev]

      - name: Run unit tests
        run: |
          python bnglonlat/tests/test_bnglonlat.py

